from .connection import connection_db

def check_table_exists():
    conn = connection_db()
    cur = conn.cursor()

    try:
        cur.execute("""
            SELECT CASE 
                     WHEN COUNT(*) > 0 THEN 'EXISTE'
                     ELSE 'NÃO EXISTE'
                   END AS tabela_status
            FROM user_tables
            WHERE table_name = 'USERS'
        """)
        status = cur.fetchone()[0]

        if status == "NÃO EXISTE":
            print("Tabela não existe. Criando...")
            creat_table()
            return False
        else:
            print("Tabela já existe.")
            return True
    except Exception as e:
        print("Erro ao executar a verificação:", e)
    finally:
        cur.close()
        conn.close()


def creat_table():
    conn = connection_db()
    cur = conn.cursor()

    try:
        cur.execute('''
            CREATE TABLE users (
                id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id      NUMBER,
                embedding    BLOB,
                metadata     CLOB,
                created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        conn.commit()
        print("Tabela criada com sucesso!")
    except Exception as e:
        print("Erro ao criar a tabela:", e)
    finally:
        cur.close()
        conn.close()