import logging
from .connection import connection_db
from config.settings import DB_LOG_FILE

# Configuração do logging
logging.basicConfig(
    filename=DB_LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)

def check_table_exists(conn):
    """
    Verifica se a tabela 'users' existe no banco.
    """
    cur = conn.cursor()
    try:
        cur.execute("""
            SELECT COUNT(*)
            FROM user_tables
            WHERE table_name = 'USERS'
        """)
        exists = cur.fetchone()[0] > 0
        if not exists:
            cur.execute('''
                CREATE TABLE users (
                    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username   VARCHAR2(100) UNIQUE NOT NULL,
                    embedding  BLOB NOT NULL,
                    metadata   CLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ''')
            conn.commit()
            logging.info("Tabela 'users' criada com sucesso!")
            return True
        return True
    except Exception as e:
        logging.error(f"❌ Erro ao verificar/criar tabela: {e}")
        return False
    finally:
        cur.close()